{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: {{ .Values.namespaces.apps | default "projet-apps" }}
  labels:
    app: webmvc
spec:
  type: {{ .Values.web.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.web.service.port | default 80 }}
      targetPort: {{ .Values.web.service.targetPort | default 80 }}
  selector:
    app: webmvc
{{- end }}
