# 1. PERMISSIONS RBAC (Inchangé)
{{- if .Values.monitoring.efk.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: ns-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: ns-monitoring
---
# 2. CONFIGURATION (Inchangé)
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: ns-monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
    [OUTPUT]
        Name          es
        Match         *
        Host          elasticsearch
        Port          9200
        Logstash_Format On
        Logstash_Prefix fluentbit
        Replace_Dots  On
        Suppress_Type_Name On
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
# 3. ELASTICSEARCH (Nettoyé de l'affinité)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: ns-monitoring
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: warshall/elasticsearch:v2.0.0
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: ns-monitoring
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
---
# 4. FLUENT BIT (DaemonSet - OK par défaut)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: ns-monitoring
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: warshall/fluent-bit:v2.0.0
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/parsers.conf
          subPath: parsers.conf
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluent-bit-config
---
# 5. KIBANA (Nettoyé de l'affinité)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: ns-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: warshall/kibana:v2.0.0
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: SERVER_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: ns-monitoring
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
---
# 6. JOB D'INITIALISATION (Nettoyé de l'affinité)
apiVersion: batch/v1
kind: Job
metadata:
  name: efk-init-job
  namespace: ns-monitoring
spec:
  template:
    spec:
      containers:
      - name: init-helper
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Attente de Elasticsearch..."
          until curl -s http://elasticsearch:9200; do sleep 5; done
          echo "Elasticsearch OK. Envoi du log de test..."
          curl -X POST "http://elasticsearch:9200/fluentbit-initial/_doc/" -H 'Content-Type: application/json' -d'
          {
            "@timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
            "message": "Stack EFK opérationnelle",
            "status": "success"
          }'
      restartPolicy: OnFailure
{{- end }}
