{{- if .Values.identity.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: {{ .Values.namespaces.apps | default "projet-apps" }}
  labels:
    app: identity-api
spec:
  type: {{ .Values.identity.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.identity.service.port | default 80 }}
      targetPort: {{ .Values.identity.service.targetPort | default 80 }}
  selector:
    app: identity-api
{{- end }}
